name: ğŸš€ CI
on: [ push, pull_request ]
jobs:
  ci:
    name: "ğŸš€ CI"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
        php-version: [ 8.3 ]
    steps:

      # --------- Setup steps ---------
      - name: "ğŸ“¦ Checkout"
        uses: actions/checkout@v3

      - name: "ğŸ˜ Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          extensions: pcov, xdebug

      - name: "ğŸ“¦ Install dependencies"
        uses: ramsey/composer-install@v2

      # --------- Run steps ---------
      - name: "ğŸ§ª Run tests"
        run: "composer test"

      - name: "ğŸ§¹ PHP CS Fixer"
        run: "composer cs-fix"

      - name: "ğŸ” Psalm"
        run: "composer psalm"
